### ISSUE TITLE
small typo

### ISSUE THREAD

**Issue by peetCreative** [AlgerP572/WeatherPi#1]
Hey,
just Minor copy-paste typo issue: Maybe use `offsetAngle` instead of `ioPin` in `BuildWindDirectionSensor` [here](https://github.com/AlgerP572/WeatherPi/blob/667cc8c5e2ed9db20c0ddc01b8f901533566d1d1/weewx4/bin/weewx/drivers/WeatherPi.py#L552)

Thanks for your Work!

**Comment by AlgerP572** [comment]
Good find. 👍   I'm making the change now.  I'm glad you have found it useful.  😃

**Comment by AlgerP572** [comment]
Marking closed now.  Has been running with the change for several days.
